/**
 * Reads admin/dist files and generates server/admin-assets.ts
 * with the content embedded as strings. This ensures the admin
 * dashboard works in production without relying on file system paths.
 */
import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join } from "path";

const adminDist = join(process.cwd(), "admin/dist");

// Read index.html
const indexHtml = readFileSync(join(adminDist, "index.html"), "utf-8");

// Read all assets
const assetsDir = join(adminDist, "assets");
const assetFiles = readdirSync(assetsDir);

const assets = {};
for (const file of assetFiles) {
  const content = readFileSync(join(assetsDir, file), "utf-8");
  assets[file] = content;
}

// Generate TypeScript file
const output = `// AUTO-GENERATED by scripts/embed-admin.mjs - DO NOT EDIT
// Contains the admin dashboard SPA files embedded as strings

export const adminIndexHtml = ${JSON.stringify(indexHtml)};

export const adminAssets: Record<string, { content: string; contentType: string }> = {
${Object.entries(assets).map(([filename, content]) => {
  const contentType = filename.endsWith(".js") ? "application/javascript" : 
                      filename.endsWith(".css") ? "text/css" : "text/plain";
  return `  ${JSON.stringify(filename)}: { content: ${JSON.stringify(content)}, contentType: ${JSON.stringify(contentType)} },`;
}).join("\n")}
};
`;

writeFileSync(join(process.cwd(), "server/admin-assets.ts"), output);
console.log(`Generated server/admin-assets.ts with ${Object.keys(assets).length} asset files`);
